//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentService.RefundNotificationAGW
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", ConfigurationName="PaymentService.RefundNotificationAGW.RefundNotificationAGW")]
    public interface RefundNotificationAGW
    {
        
        // CODEGEN: Generating message contract since the operation RefundNotificationAGW is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RefundNotificationAGW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RefundRec_Type))]
        PaymentService.RefundNotificationAGW.RefundNotificationAGWResponse RefundNotificationAGW(PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RefundNotificationAGW", ReplyAction="*")]
        System.Threading.Tasks.Task<PaymentService.RefundNotificationAGW.RefundNotificationAGWResponse> RefundNotificationAGWAsync(PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class RefundNotificationAGWRq_Type
    {
        
        private MsgRqHdr_Type msgRqHdrField;
        
        private RefundNotificationAGWRqBody_Type bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRqHdr_Type MsgRqHdr
        {
            get
            {
                return this.msgRqHdrField;
            }
            set
            {
                this.msgRqHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RefundNotificationAGWRqBody_Type Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRqHdr_Type
    {
        
        private string rqUIDField;
        
        private SCId_Type sCIdField;
        
        private string funcIdField;
        
        private PartnerInfo_Type partnerInfoField;
        
        private long rqModeField;
        
        private bool rqModeFieldSpecified;
        
        private PartyId_Type partyIdField;
        
        private string userIdField;
        
        private string proxyUserIdField;
        
        private System.DateTime clientDtField;
        
        private string echoDataField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SCId_Type SCId
        {
            get
            {
                return this.sCIdField;
            }
            set
            {
                this.sCIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FuncId
        {
            get
            {
                return this.funcIdField;
            }
            set
            {
                this.funcIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PartnerInfo_Type PartnerInfo
        {
            get
            {
                return this.partnerInfoField;
            }
            set
            {
                this.partnerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long RqMode
        {
            get
            {
                return this.rqModeField;
            }
            set
            {
                this.rqModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RqModeSpecified
        {
            get
            {
                return this.rqModeFieldSpecified;
            }
            set
            {
                this.rqModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PartyId_Type PartyId
        {
            get
            {
                return this.partyIdField;
            }
            set
            {
                this.partyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ProxyUserId
        {
            get
            {
                return this.proxyUserIdField;
            }
            set
            {
                this.proxyUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime ClientDt
        {
            get
            {
                return this.clientDtField;
            }
            set
            {
                this.clientDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum SCId_Type
    {
        
        /// <remarks/>
        G2G,
        
        /// <remarks/>
        ECLLCTN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartnerInfo_Type
    {
        
        private string partnerIdField;
        
        private PartnerType_Type partnerTypeField;
        
        private string partnerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartnerType_Type PartnerType
        {
            get
            {
                return this.partnerTypeField;
            }
            set
            {
                this.partnerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartnerType_Type
    {
        
        /// <remarks/>
        GOVT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class Status_Type
    {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc
        {
            get
            {
                return this.statusDescField;
            }
            set
            {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRsHdr_Type
    {
        
        private string rqUIDField;
        
        private string sPRefNumField;
        
        private string msgRecDtField;
        
        private Status_Type statusField;
        
        private string echoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SPRefNum
        {
            get
            {
                return this.sPRefNumField;
            }
            set
            {
                this.sPRefNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgRecDt
        {
            get
            {
                return this.msgRecDtField;
            }
            set
            {
                this.msgRecDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Status_Type Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class RefundNotificationAGWRs_Type
    {
        
        private MsgRsHdr_Type msgRsHdrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRsHdr_Type MsgRsHdr
        {
            get
            {
                return this.msgRsHdrField;
            }
            set
            {
                this.msgRsHdrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class RevenueEntryInfo_Type
    {
        
        private string benAgencyIdField;
        
        private string gFSCodeField;
        
        private decimal amtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BenAgencyId
        {
            get
            {
                return this.benAgencyIdField;
            }
            set
            {
                this.benAgencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GFSCode
        {
            get
            {
                return this.gFSCodeField;
            }
            set
            {
                this.gFSCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Amt
        {
            get
            {
                return this.amtField;
            }
            set
            {
                this.amtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class POI_Type
    {
        
        private string pOINumField;
        
        private POIType_Type pOITypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string POINum
        {
            get
            {
                return this.pOINumField;
            }
            set
            {
                this.pOINumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public POIType_Type POIType
        {
            get
            {
                return this.pOITypeField;
            }
            set
            {
                this.pOITypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum POIType_Type
    {
        
        /// <remarks/>
        NAT,
        
        /// <remarks/>
        IQA,
        
        /// <remarks/>
        BIS,
        
        /// <remarks/>
        UOI,
        
        /// <remarks/>
        C700,
        
        /// <remarks/>
        GCC,
        
        /// <remarks/>
        PAS,
        
        /// <remarks/>
        BDN,
        
        /// <remarks/>
        FCN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class SADADStatus_Type
    {
        
        private string sADADStatusCodeField;
        
        private string sADADStatusDescField;
        
        private SADADStatusSeverity_Type sADADStatusSeverityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SADADStatusCode
        {
            get
            {
                return this.sADADStatusCodeField;
            }
            set
            {
                this.sADADStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SADADStatusDesc
        {
            get
            {
                return this.sADADStatusDescField;
            }
            set
            {
                this.sADADStatusDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SADADStatusSeverity_Type SADADStatusSeverity
        {
            get
            {
                return this.sADADStatusSeverityField;
            }
            set
            {
                this.sADADStatusSeverityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum SADADStatusSeverity_Type
    {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Info,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RefundInfo_Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class RefundRec_Type
    {
        
        private string agencyIdField;
        
        private string billerRefundIdField;
        
        private string agencyRefundIdField;
        
        private string eCollectionRefundIdField;
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string sADADPmtIdField;
        
        private decimal refundAmtField;
        
        private bool refundAmtFieldSpecified;
        
        private string refundDtField;
        
        private string expDtField;
        
        private eCollectionRefundMethod_Type eCollectionRefundMethodField;
        
        private bool eCollectionRefundMethodFieldSpecified;
        
        private string eCollectionRefundMethodReconDtField;
        
        private RefundStatusCode_Type refundStatusCodeField;
        
        private bool refundStatusCodeFieldSpecified;
        
        private SADADStatus_Type sADADRefundStatusField;
        
        private string refundRefInfoField;
        
        private string actionReasonField;
        
        private POI_Type payeePOIField;
        
        private RevenueEntryInfo_Type[] revenueEntryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AgencyId
        {
            get
            {
                return this.agencyIdField;
            }
            set
            {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BillerRefundId
        {
            get
            {
                return this.billerRefundIdField;
            }
            set
            {
                this.billerRefundIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AgencyRefundId
        {
            get
            {
                return this.agencyRefundIdField;
            }
            set
            {
                this.agencyRefundIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string eCollectionRefundId
        {
            get
            {
                return this.eCollectionRefundIdField;
            }
            set
            {
                this.eCollectionRefundIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayeeBankAcct", typeof(string), Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("PayeeBankId", typeof(string), Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("eCollectionPmtId", typeof(string), Order=4)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=5)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SADADPmtId
        {
            get
            {
                return this.sADADPmtIdField;
            }
            set
            {
                this.sADADPmtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal RefundAmt
        {
            get
            {
                return this.refundAmtField;
            }
            set
            {
                this.refundAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RefundAmtSpecified
        {
            get
            {
                return this.refundAmtFieldSpecified;
            }
            set
            {
                this.refundAmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RefundDt
        {
            get
            {
                return this.refundDtField;
            }
            set
            {
                this.refundDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ExpDt
        {
            get
            {
                return this.expDtField;
            }
            set
            {
                this.expDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public eCollectionRefundMethod_Type eCollectionRefundMethod
        {
            get
            {
                return this.eCollectionRefundMethodField;
            }
            set
            {
                this.eCollectionRefundMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eCollectionRefundMethodSpecified
        {
            get
            {
                return this.eCollectionRefundMethodFieldSpecified;
            }
            set
            {
                this.eCollectionRefundMethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string eCollectionRefundMethodReconDt
        {
            get
            {
                return this.eCollectionRefundMethodReconDtField;
            }
            set
            {
                this.eCollectionRefundMethodReconDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public RefundStatusCode_Type RefundStatusCode
        {
            get
            {
                return this.refundStatusCodeField;
            }
            set
            {
                this.refundStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RefundStatusCodeSpecified
        {
            get
            {
                return this.refundStatusCodeFieldSpecified;
            }
            set
            {
                this.refundStatusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public SADADStatus_Type SADADRefundStatus
        {
            get
            {
                return this.sADADRefundStatusField;
            }
            set
            {
                this.sADADRefundStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RefundRefInfo
        {
            get
            {
                return this.refundRefInfoField;
            }
            set
            {
                this.refundRefInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ActionReason
        {
            get
            {
                return this.actionReasonField;
            }
            set
            {
                this.actionReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public POI_Type PayeePOI
        {
            get
            {
                return this.payeePOIField;
            }
            set
            {
                this.payeePOIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RevenueEntryInfo", IsNullable=false)]
        public RevenueEntryInfo_Type[] RevenueEntryList
        {
            get
            {
                return this.revenueEntryListField;
            }
            set
            {
                this.revenueEntryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        PayeeBankAcct,
        
        /// <remarks/>
        PayeeBankId,
        
        /// <remarks/>
        eCollectionPmtId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum eCollectionRefundMethod_Type
    {
        
        /// <remarks/>
        SADAD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum RefundStatusCode_Type
    {
        
        /// <remarks/>
        Succeeded,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class RefundInfo_Type : RefundRec_Type
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class RefundNotificationAGWRqBody_Type
    {
        
        private RefundInfo_Type[] refundListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RefundInfo", IsNullable=false)]
        public RefundInfo_Type[] RefundList
        {
            get
            {
                return this.refundListField;
            }
            set
            {
                this.refundListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartyId_Type
    {
        
        private string partyIdNumField;
        
        private PartyIdType_Type partyIdTypeField;
        
        private bool partyIdTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartyIdNum
        {
            get
            {
                return this.partyIdNumField;
            }
            set
            {
                this.partyIdNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartyIdType_Type PartyIdType
        {
            get
            {
                return this.partyIdTypeField;
            }
            set
            {
                this.partyIdTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartyIdTypeSpecified
        {
            get
            {
                return this.partyIdTypeFieldSpecified;
            }
            set
            {
                this.partyIdTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartyIdType_Type
    {
        
        /// <remarks/>
        IqamaNumber,
        
        /// <remarks/>
        NationalId,
        
        /// <remarks/>
        CommercialRegistration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("700Code")]
        Item700Code,
        
        /// <remarks/>
        AccountNumber,
        
        /// <remarks/>
        FamilyCardNumber,
        
        /// <remarks/>
        BorderNumber,
        
        /// <remarks/>
        PassportNumber,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundNotificationAGWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.RefundNotificationAGW.RefundNotificationAGWRq_Type RefundNotificationAGWRq;
        
        public RefundNotificationAGWRequest()
        {
        }
        
        public RefundNotificationAGWRequest(PaymentService.RefundNotificationAGW.RefundNotificationAGWRq_Type RefundNotificationAGWRq)
        {
            this.RefundNotificationAGWRq = RefundNotificationAGWRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundNotificationAGWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.RefundNotificationAGW.RefundNotificationAGWRs_Type RefundNotificationAGWRs;
        
        public RefundNotificationAGWResponse()
        {
        }
        
        public RefundNotificationAGWResponse(PaymentService.RefundNotificationAGW.RefundNotificationAGWRs_Type RefundNotificationAGWRs)
        {
            this.RefundNotificationAGWRs = RefundNotificationAGWRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface RefundNotificationAGWChannel : PaymentService.RefundNotificationAGW.RefundNotificationAGW, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RefundNotificationAGWClient : System.ServiceModel.ClientBase<PaymentService.RefundNotificationAGW.RefundNotificationAGW>, PaymentService.RefundNotificationAGW.RefundNotificationAGW
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RefundNotificationAGWClient() : 
                base(RefundNotificationAGWClient.GetDefaultBinding(), RefundNotificationAGWClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RefundNotificationAGW.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefundNotificationAGWClient(EndpointConfiguration endpointConfiguration) : 
                base(RefundNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), RefundNotificationAGWClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefundNotificationAGWClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RefundNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefundNotificationAGWClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RefundNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefundNotificationAGWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaymentService.RefundNotificationAGW.RefundNotificationAGWResponse PaymentService.RefundNotificationAGW.RefundNotificationAGW.RefundNotificationAGW(PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest request)
        {
            return base.Channel.RefundNotificationAGW(request);
        }
        
        public PaymentService.RefundNotificationAGW.RefundNotificationAGWRs_Type RefundNotificationAGW(PaymentService.RefundNotificationAGW.RefundNotificationAGWRq_Type RefundNotificationAGWRq)
        {
            PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest inValue = new PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest();
            inValue.RefundNotificationAGWRq = RefundNotificationAGWRq;
            PaymentService.RefundNotificationAGW.RefundNotificationAGWResponse retVal = ((PaymentService.RefundNotificationAGW.RefundNotificationAGW)(this)).RefundNotificationAGW(inValue);
            return retVal.RefundNotificationAGWRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentService.RefundNotificationAGW.RefundNotificationAGWResponse> PaymentService.RefundNotificationAGW.RefundNotificationAGW.RefundNotificationAGWAsync(PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest request)
        {
            return base.Channel.RefundNotificationAGWAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentService.RefundNotificationAGW.RefundNotificationAGWResponse> RefundNotificationAGWAsync(PaymentService.RefundNotificationAGW.RefundNotificationAGWRq_Type RefundNotificationAGWRq)
        {
            PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest inValue = new PaymentService.RefundNotificationAGW.RefundNotificationAGWRequest();
            inValue.RefundNotificationAGWRq = RefundNotificationAGWRq;
            return ((PaymentService.RefundNotificationAGW.RefundNotificationAGW)(this)).RefundNotificationAGWAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RefundNotificationAGW))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RefundNotificationAGW))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7001/RefundNotificationAGW");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RefundNotificationAGWClient.GetBindingForEndpoint(EndpointConfiguration.RefundNotificationAGW);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RefundNotificationAGWClient.GetEndpointAddress(EndpointConfiguration.RefundNotificationAGW);
        }
        
        public enum EndpointConfiguration
        {
            
            RefundNotificationAGW,
        }
    }
}
