//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.DTO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTranslationAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslationAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Training.DTO.ResTranslationAr", typeof(ResTranslationAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستكمال التسجيل في الانتظار.
        /// </summary>
        public static string CompeleteInWaitingList {
            get {
                return ResourceManager.GetString("CompeleteInWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستكمال التسجيل.
        /// </summary>
        public static string CompleteRegisterInCourse {
            get {
                return ResourceManager.GetString("CompleteRegisterInCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستبعد.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثي.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حكومي.
        /// </summary>
        public static string Government {
            get {
                return ResourceManager.GetString("Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهات حكومية اخري.
        /// </summary>
        public static string GovernmentOther {
            get {
                return ResourceManager.GetString("GovernmentOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عالى.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منخفض.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجل.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        public static string Med {
            get {
                return ResourceManager.GetString("Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان ترفق خطاب الموافقة للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingApprovalLetter {
            get {
                return ResourceManager.GetString("MissingApprovalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل رقم المبني للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingBuildingNumber {
            get {
                return ResourceManager.GetString("MissingBuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل الادارة لتكمل للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingDepartment {
            get {
                return ResourceManager.GetString("MissingDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تملئ نموذج حفظ الطاقة للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingEnergySaveingForm {
            get {
                return ResourceManager.GetString("MissingEnergySaveingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تملئ نموذج الاكسل للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingExcel {
            get {
                return ResourceManager.GetString("MissingExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل الرمز الاضافي للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingExtraCode {
            get {
                return ResourceManager.GetString("MissingExtraCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل المسمي الوظيفي للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingJobDescription {
            get {
                return ResourceManager.GetString("MissingJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل المنصب للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingPosition {
            get {
                return ResourceManager.GetString("MissingPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل الرقم البريدي للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingPostalCode {
            get {
                return ResourceManager.GetString("MissingPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل بيانات البريد السعودي للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingSaduiPostal {
            get {
                return ResourceManager.GetString("MissingSaduiPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل المؤهل الدراسي للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingSchoolCertificate {
            get {
                return ResourceManager.GetString("MissingSchoolCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تدخل رقم الشارع للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingStreetNumber {
            get {
                return ResourceManager.GetString("MissingStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تملئ نموذج الورد للتسجيل في هذة الدورة.
        /// </summary>
        public static string MissingWord {
            get {
                return ResourceManager.GetString("MissingWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير حكومي.
        /// </summary>
        public static string NonGovernment {
            get {
                return ResourceManager.GetString("NonGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير ممسوح.
        /// </summary>
        public static string NotDeleted {
            get {
                return ResourceManager.GetString("NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مستهدف.
        /// </summary>
        public static string NotTargeted {
            get {
                return ResourceManager.GetString("NotTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا في تعريف جوجل.
        /// </summary>
        public static string ReCaptchaError {
            get {
                return ResourceManager.GetString("ReCaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في قراءة تعريف جوجل.
        /// </summary>
        public static string ReCaptchaError1 {
            get {
                return ResourceManager.GetString("ReCaptchaError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أغلق التسجيل.
        /// </summary>
        public static string RegEneded {
            get {
                return ResourceManager.GetString("RegEneded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الدورة.
        /// </summary>
        public static string RegisterInCourse {
            get {
                return ResourceManager.GetString("RegisterInCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في مقاعد الانتظار.
        /// </summary>
        public static string RegisterInWaitingList {
            get {
                return ResourceManager.GetString("RegisterInWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسجيل.
        /// </summary>
        public static string RegistrationDone {
            get {
                return ResourceManager.GetString("RegistrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسجيل في مقاعد الانتظار.
        /// </summary>
        public static string RegistrationDoneInWaitingList {
            get {
                return ResourceManager.GetString("RegistrationDoneInWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشترك.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مشترك.
        /// </summary>
        public static string UnSubscribe {
            get {
                return ResourceManager.GetString("UnSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الانتظار.
        /// </summary>
        public static string Waitinglist {
            get {
                return ResourceManager.GetString("Waitinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
