//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.DTO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTranslationEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslationEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Training.DTO.ResTranslationEn", typeof(ResTranslationEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete In Waiting List.
        /// </summary>
        public static string CompeleteInWaitingList {
            get {
                return ResourceManager.GetString("CompeleteInWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Course Registration.
        /// </summary>
        public static string CompleteRegisterInCourse {
            get {
                return ResourceManager.GetString("CompleteRegisterInCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        public static string Government {
            get {
                return ResourceManager.GetString("Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Other.
        /// </summary>
        public static string GovernmentOther {
            get {
                return ResourceManager.GetString("GovernmentOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Status.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med.
        /// </summary>
        public static string Med {
            get {
                return ResourceManager.GetString("Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Government.
        /// </summary>
        public static string NonGovernment {
            get {
                return ResourceManager.GetString("NonGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Deleted.
        /// </summary>
        public static string NotDeleted {
            get {
                return ResourceManager.GetString("NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Targeted.
        /// </summary>
        public static string NotTargeted {
            get {
                return ResourceManager.GetString("NotTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCaptcha Error.
        /// </summary>
        public static string ReCaptchaError {
            get {
                return ResourceManager.GetString("ReCaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisration Ended.
        /// </summary>
        public static string RegEneded {
            get {
                return ResourceManager.GetString("RegEneded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register In Course.
        /// </summary>
        public static string RegisterInCourse {
            get {
                return ResourceManager.GetString("RegisterInCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register In Waiting List.
        /// </summary>
        public static string RegisterInWaitingList {
            get {
                return ResourceManager.GetString("RegisterInWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Done.
        /// </summary>
        public static string RegistrationDone {
            get {
                return ResourceManager.GetString("RegistrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسجيل في مقاعد الانتظار.
        /// </summary>
        public static string RegistrationDoneInWaitingList {
            get {
                return ResourceManager.GetString("RegistrationDoneInWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSubscribe.
        /// </summary>
        public static string UnSubscribe {
            get {
                return ResourceManager.GetString("UnSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting list.
        /// </summary>
        public static string Waitinglist {
            get {
                return ResourceManager.GetString("Waitinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
