//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentService.AcctsUploadNotificationAGW
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", ConfigurationName="PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW")]
    public interface AcctsUploadNotificationAGW
    {
        
        // CODEGEN: Generating message contract since the operation AcctsUploadNotificationAGW is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AcctsUploadNotificationAGW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWResponse AcctsUploadNotificationAGW(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AcctsUploadNotificationAGW", ReplyAction="*")]
        System.Threading.Tasks.Task<PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWResponse> AcctsUploadNotificationAGWAsync(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class AcctsUploadNotificationAGWRq_Type
    {
        
        private MsgRqHdr_Type msgRqHdrField;
        
        private AcctsUploadNotificationAGWRqBody_Type bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRqHdr_Type MsgRqHdr
        {
            get
            {
                return this.msgRqHdrField;
            }
            set
            {
                this.msgRqHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AcctsUploadNotificationAGWRqBody_Type Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRqHdr_Type
    {
        
        private string rqUIDField;
        
        private SCId_Type sCIdField;
        
        private string funcIdField;
        
        private PartnerInfo_Type partnerInfoField;
        
        private long rqModeField;
        
        private bool rqModeFieldSpecified;
        
        private PartyId_Type partyIdField;
        
        private string userIdField;
        
        private string proxyUserIdField;
        
        private System.DateTime clientDtField;
        
        private string echoDataField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SCId_Type SCId
        {
            get
            {
                return this.sCIdField;
            }
            set
            {
                this.sCIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FuncId
        {
            get
            {
                return this.funcIdField;
            }
            set
            {
                this.funcIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PartnerInfo_Type PartnerInfo
        {
            get
            {
                return this.partnerInfoField;
            }
            set
            {
                this.partnerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long RqMode
        {
            get
            {
                return this.rqModeField;
            }
            set
            {
                this.rqModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RqModeSpecified
        {
            get
            {
                return this.rqModeFieldSpecified;
            }
            set
            {
                this.rqModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PartyId_Type PartyId
        {
            get
            {
                return this.partyIdField;
            }
            set
            {
                this.partyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ProxyUserId
        {
            get
            {
                return this.proxyUserIdField;
            }
            set
            {
                this.proxyUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime ClientDt
        {
            get
            {
                return this.clientDtField;
            }
            set
            {
                this.clientDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum SCId_Type
    {
        
        /// <remarks/>
        G2G,
        
        /// <remarks/>
        ECLLCTN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartnerInfo_Type
    {
        
        private string partnerIdField;
        
        private PartnerType_Type partnerTypeField;
        
        private string partnerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartnerType_Type PartnerType
        {
            get
            {
                return this.partnerTypeField;
            }
            set
            {
                this.partnerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartnerType_Type
    {
        
        /// <remarks/>
        GOVT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRsHdr_Type
    {
        
        private string rqUIDField;
        
        private string sPRefNumField;
        
        private string msgRecDtField;
        
        private Status_Type statusField;
        
        private string echoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SPRefNum
        {
            get
            {
                return this.sPRefNumField;
            }
            set
            {
                this.sPRefNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgRecDt
        {
            get
            {
                return this.msgRecDtField;
            }
            set
            {
                this.msgRecDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Status_Type Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class Status_Type
    {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc
        {
            get
            {
                return this.statusDescField;
            }
            set
            {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class AcctsUploadNotificationAGWRs_Type
    {
        
        private MsgRsHdr_Type msgRsHdrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRsHdr_Type MsgRsHdr
        {
            get
            {
                return this.msgRsHdrField;
            }
            set
            {
                this.msgRsHdrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class AcctErrorInfo_Type
    {
        
        private Status_Type errorStatusField;
        
        private string agencyIdField;
        
        private string billAcctField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status_Type ErrorStatus
        {
            get
            {
                return this.errorStatusField;
            }
            set
            {
                this.errorStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AgencyId
        {
            get
            {
                return this.agencyIdField;
            }
            set
            {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BillAcct
        {
            get
            {
                return this.billAcctField;
            }
            set
            {
                this.billAcctField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class AcctsUploadNotificationAGWRqBody_Type
    {
        
        private string batchIdField;
        
        private long successRecsCountField;
        
        private long errorRecsCountField;
        
        private AcctErrorInfo_Type[] acctErrorListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BatchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long SuccessRecsCount
        {
            get
            {
                return this.successRecsCountField;
            }
            set
            {
                this.successRecsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ErrorRecsCount
        {
            get
            {
                return this.errorRecsCountField;
            }
            set
            {
                this.errorRecsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AcctErrorInfo", IsNullable=false)]
        public AcctErrorInfo_Type[] AcctErrorList
        {
            get
            {
                return this.acctErrorListField;
            }
            set
            {
                this.acctErrorListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartyId_Type
    {
        
        private string partyIdNumField;
        
        private PartyIdType_Type partyIdTypeField;
        
        private bool partyIdTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartyIdNum
        {
            get
            {
                return this.partyIdNumField;
            }
            set
            {
                this.partyIdNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartyIdType_Type PartyIdType
        {
            get
            {
                return this.partyIdTypeField;
            }
            set
            {
                this.partyIdTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartyIdTypeSpecified
        {
            get
            {
                return this.partyIdTypeFieldSpecified;
            }
            set
            {
                this.partyIdTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartyIdType_Type
    {
        
        /// <remarks/>
        IqamaNumber,
        
        /// <remarks/>
        NationalId,
        
        /// <remarks/>
        CommercialRegistration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("700Code")]
        Item700Code,
        
        /// <remarks/>
        AccountNumber,
        
        /// <remarks/>
        FamilyCardNumber,
        
        /// <remarks/>
        BorderNumber,
        
        /// <remarks/>
        PassportNumber,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcctsUploadNotificationAGWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRq_Type AcctsUploadNotificationAGWRq;
        
        public AcctsUploadNotificationAGWRequest()
        {
        }
        
        public AcctsUploadNotificationAGWRequest(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRq_Type AcctsUploadNotificationAGWRq)
        {
            this.AcctsUploadNotificationAGWRq = AcctsUploadNotificationAGWRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcctsUploadNotificationAGWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRs_Type AcctsUploadNotificationAGWRs;
        
        public AcctsUploadNotificationAGWResponse()
        {
        }
        
        public AcctsUploadNotificationAGWResponse(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRs_Type AcctsUploadNotificationAGWRs)
        {
            this.AcctsUploadNotificationAGWRs = AcctsUploadNotificationAGWRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AcctsUploadNotificationAGWChannel : PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AcctsUploadNotificationAGWClient : System.ServiceModel.ClientBase<PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW>, PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AcctsUploadNotificationAGWClient() : 
                base(AcctsUploadNotificationAGWClient.GetDefaultBinding(), AcctsUploadNotificationAGWClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AcctsUploadNotificationAGWSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcctsUploadNotificationAGWClient(EndpointConfiguration endpointConfiguration) : 
                base(AcctsUploadNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), AcctsUploadNotificationAGWClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcctsUploadNotificationAGWClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AcctsUploadNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcctsUploadNotificationAGWClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AcctsUploadNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcctsUploadNotificationAGWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWResponse PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest request)
        {
            return base.Channel.AcctsUploadNotificationAGW(request);
        }
        
        public PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRs_Type AcctsUploadNotificationAGW(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRq_Type AcctsUploadNotificationAGWRq)
        {
            PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest inValue = new PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest();
            inValue.AcctsUploadNotificationAGWRq = AcctsUploadNotificationAGWRq;
            PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWResponse retVal = ((PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW)(this)).AcctsUploadNotificationAGW(inValue);
            return retVal.AcctsUploadNotificationAGWRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWResponse> PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWAsync(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest request)
        {
            return base.Channel.AcctsUploadNotificationAGWAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWResponse> AcctsUploadNotificationAGWAsync(PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRq_Type AcctsUploadNotificationAGWRq)
        {
            PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest inValue = new PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGWRequest();
            inValue.AcctsUploadNotificationAGWRq = AcctsUploadNotificationAGWRq;
            return ((PaymentService.AcctsUploadNotificationAGW.AcctsUploadNotificationAGW)(this)).AcctsUploadNotificationAGWAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AcctsUploadNotificationAGWSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AcctsUploadNotificationAGWSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7800/AcctsUploadNotificationAGW");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AcctsUploadNotificationAGWClient.GetBindingForEndpoint(EndpointConfiguration.AcctsUploadNotificationAGWSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AcctsUploadNotificationAGWClient.GetEndpointAddress(EndpointConfiguration.AcctsUploadNotificationAGWSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            AcctsUploadNotificationAGWSOAP,
        }
    }
}
