//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentService.PmtNotificationAGW
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", ConfigurationName="PaymentService.PmtNotificationAGW.PmtNotificationAGW")]
    public interface PmtNotificationAGW
    {
        
        // CODEGEN: Generating message contract since the operation PmtNotificationAGW is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="PmtNotificationAGW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PmtRec_Type))]
        PaymentService.PmtNotificationAGW.PmtNotificationAGWResponse PmtNotificationAGW(PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PmtNotificationAGW", ReplyAction="*")]
        System.Threading.Tasks.Task<PaymentService.PmtNotificationAGW.PmtNotificationAGWResponse> PmtNotificationAGWAsync(PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PmtNotificationAGWRq_Type
    {
        
        private MsgRqHdr_Type msgRqHdrField;
        
        private PmtNotificationAGWRqBody_Type bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRqHdr_Type MsgRqHdr
        {
            get
            {
                return this.msgRqHdrField;
            }
            set
            {
                this.msgRqHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PmtNotificationAGWRqBody_Type Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRqHdr_Type
    {
        
        private string rqUIDField;
        
        private SCId_Type sCIdField;
        
        private string funcIdField;
        
        private PartnerInfo_Type partnerInfoField;
        
        private long rqModeField;
        
        private bool rqModeFieldSpecified;
        
        private PartyId_Type partyIdField;
        
        private string userIdField;
        
        private string proxyUserIdField;
        
        private System.DateTime clientDtField;
        
        private string echoDataField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SCId_Type SCId
        {
            get
            {
                return this.sCIdField;
            }
            set
            {
                this.sCIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FuncId
        {
            get
            {
                return this.funcIdField;
            }
            set
            {
                this.funcIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PartnerInfo_Type PartnerInfo
        {
            get
            {
                return this.partnerInfoField;
            }
            set
            {
                this.partnerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long RqMode
        {
            get
            {
                return this.rqModeField;
            }
            set
            {
                this.rqModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RqModeSpecified
        {
            get
            {
                return this.rqModeFieldSpecified;
            }
            set
            {
                this.rqModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PartyId_Type PartyId
        {
            get
            {
                return this.partyIdField;
            }
            set
            {
                this.partyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ProxyUserId
        {
            get
            {
                return this.proxyUserIdField;
            }
            set
            {
                this.proxyUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime ClientDt
        {
            get
            {
                return this.clientDtField;
            }
            set
            {
                this.clientDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum SCId_Type
    {
        
        /// <remarks/>
        G2G,
        
        /// <remarks/>
        ECLLCTN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartnerInfo_Type
    {
        
        private string partnerIdField;
        
        private PartnerType_Type partnerTypeField;
        
        private string partnerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartnerType_Type PartnerType
        {
            get
            {
                return this.partnerTypeField;
            }
            set
            {
                this.partnerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartnerType_Type
    {
        
        /// <remarks/>
        GOVT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class Status_Type
    {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc
        {
            get
            {
                return this.statusDescField;
            }
            set
            {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRsHdr_Type
    {
        
        private string rqUIDField;
        
        private string sPRefNumField;
        
        private string msgRecDtField;
        
        private Status_Type statusField;
        
        private string echoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SPRefNum
        {
            get
            {
                return this.sPRefNumField;
            }
            set
            {
                this.sPRefNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgRecDt
        {
            get
            {
                return this.msgRecDtField;
            }
            set
            {
                this.msgRecDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Status_Type Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PmtNotificationAGWRs_Type
    {
        
        private MsgRsHdr_Type msgRsHdrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRsHdr_Type MsgRsHdr
        {
            get
            {
                return this.msgRsHdrField;
            }
            set
            {
                this.msgRsHdrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class POI_Type
    {
        
        private string pOINumField;
        
        private POIType_Type pOITypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string POINum
        {
            get
            {
                return this.pOINumField;
            }
            set
            {
                this.pOINumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public POIType_Type POIType
        {
            get
            {
                return this.pOITypeField;
            }
            set
            {
                this.pOITypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum POIType_Type
    {
        
        /// <remarks/>
        NAT,
        
        /// <remarks/>
        IQA,
        
        /// <remarks/>
        BIS,
        
        /// <remarks/>
        UOI,
        
        /// <remarks/>
        C700,
        
        /// <remarks/>
        GCC,
        
        /// <remarks/>
        PAS,
        
        /// <remarks/>
        BDN,
        
        /// <remarks/>
        FCN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class eCollectionPmtMethodDtls_Type
    {
        
        private string pmtIdField;
        
        private string bankIdField;
        
        private string bankPmtIdField;
        
        private string pmtChannelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PmtId
        {
            get
            {
                return this.pmtIdField;
            }
            set
            {
                this.pmtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BankId
        {
            get
            {
                return this.bankIdField;
            }
            set
            {
                this.bankIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BankPmtId
        {
            get
            {
                return this.bankPmtIdField;
            }
            set
            {
                this.bankPmtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PmtChannel
        {
            get
            {
                return this.pmtChannelField;
            }
            set
            {
                this.pmtChannelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PmtInfo_Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PmtRec_Type
    {
        
        private string agencyIdField;
        
        private string billerPmtIdField;
        
        private string agencyPmtIdField;
        
        private string eCollectionPmtIdField;
        
        private string billNumField;
        
        private string billAcctField;
        
        private string billCategoryField;
        
        private string billCycleField;
        
        private decimal pmtAmtField;
        
        private string pmtDtField;
        
        private string pmtCollectDtField;
        
        private PmtMethod_Type pmtMethodField;
        
        private bool pmtMethodFieldSpecified;
        
        private eCollectionPmtMethod_Type eCollectionPmtMethodField;
        
        private bool eCollectionPmtMethodFieldSpecified;
        
        private string eCollectionPmtMethodReconDtField;
        
        private eCollectionPmtMethodDtls_Type eCollectionPmtMethodDtlsField;
        
        private PmtStatusCode_Type pmtStatusCodeField;
        
        private bool pmtStatusCodeFieldSpecified;
        
        private string pmtRefInfoField;
        
        private POI_Type payorPOIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AgencyId
        {
            get
            {
                return this.agencyIdField;
            }
            set
            {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BillerPmtId
        {
            get
            {
                return this.billerPmtIdField;
            }
            set
            {
                this.billerPmtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AgencyPmtId
        {
            get
            {
                return this.agencyPmtIdField;
            }
            set
            {
                this.agencyPmtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string eCollectionPmtId
        {
            get
            {
                return this.eCollectionPmtIdField;
            }
            set
            {
                this.eCollectionPmtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BillNum
        {
            get
            {
                return this.billNumField;
            }
            set
            {
                this.billNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BillAcct
        {
            get
            {
                return this.billAcctField;
            }
            set
            {
                this.billAcctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BillCategory
        {
            get
            {
                return this.billCategoryField;
            }
            set
            {
                this.billCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BillCycle
        {
            get
            {
                return this.billCycleField;
            }
            set
            {
                this.billCycleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal PmtAmt
        {
            get
            {
                return this.pmtAmtField;
            }
            set
            {
                this.pmtAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PmtDt
        {
            get
            {
                return this.pmtDtField;
            }
            set
            {
                this.pmtDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PmtCollectDt
        {
            get
            {
                return this.pmtCollectDtField;
            }
            set
            {
                this.pmtCollectDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public PmtMethod_Type PmtMethod
        {
            get
            {
                return this.pmtMethodField;
            }
            set
            {
                this.pmtMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PmtMethodSpecified
        {
            get
            {
                return this.pmtMethodFieldSpecified;
            }
            set
            {
                this.pmtMethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public eCollectionPmtMethod_Type eCollectionPmtMethod
        {
            get
            {
                return this.eCollectionPmtMethodField;
            }
            set
            {
                this.eCollectionPmtMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eCollectionPmtMethodSpecified
        {
            get
            {
                return this.eCollectionPmtMethodFieldSpecified;
            }
            set
            {
                this.eCollectionPmtMethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string eCollectionPmtMethodReconDt
        {
            get
            {
                return this.eCollectionPmtMethodReconDtField;
            }
            set
            {
                this.eCollectionPmtMethodReconDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public eCollectionPmtMethodDtls_Type eCollectionPmtMethodDtls
        {
            get
            {
                return this.eCollectionPmtMethodDtlsField;
            }
            set
            {
                this.eCollectionPmtMethodDtlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public PmtStatusCode_Type PmtStatusCode
        {
            get
            {
                return this.pmtStatusCodeField;
            }
            set
            {
                this.pmtStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PmtStatusCodeSpecified
        {
            get
            {
                return this.pmtStatusCodeFieldSpecified;
            }
            set
            {
                this.pmtStatusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PmtRefInfo
        {
            get
            {
                return this.pmtRefInfoField;
            }
            set
            {
                this.pmtRefInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public POI_Type PayorPOI
        {
            get
            {
                return this.payorPOIField;
            }
            set
            {
                this.payorPOIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PmtMethod_Type
    {
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        CHEQUE,
        
        /// <remarks/>
        TRANSFER,
        
        /// <remarks/>
        POS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum eCollectionPmtMethod_Type
    {
        
        /// <remarks/>
        SADAD,
        
        /// <remarks/>
        EFT,
        
        /// <remarks/>
        CCARD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PmtStatusCode_Type
    {
        
        /// <remarks/>
        Succeeded,
        
        /// <remarks/>
        Reversed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PmtInfo_Type : PmtRec_Type
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PmtNotificationAGWRqBody_Type
    {
        
        private PmtInfo_Type[] pmtListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PmtInfo", IsNullable=false)]
        public PmtInfo_Type[] PmtList
        {
            get
            {
                return this.pmtListField;
            }
            set
            {
                this.pmtListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartyId_Type
    {
        
        private string partyIdNumField;
        
        private PartyIdType_Type partyIdTypeField;
        
        private bool partyIdTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartyIdNum
        {
            get
            {
                return this.partyIdNumField;
            }
            set
            {
                this.partyIdNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartyIdType_Type PartyIdType
        {
            get
            {
                return this.partyIdTypeField;
            }
            set
            {
                this.partyIdTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartyIdTypeSpecified
        {
            get
            {
                return this.partyIdTypeFieldSpecified;
            }
            set
            {
                this.partyIdTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartyIdType_Type
    {
        
        /// <remarks/>
        IqamaNumber,
        
        /// <remarks/>
        NationalId,
        
        /// <remarks/>
        CommercialRegistration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("700Code")]
        Item700Code,
        
        /// <remarks/>
        AccountNumber,
        
        /// <remarks/>
        FamilyCardNumber,
        
        /// <remarks/>
        BorderNumber,
        
        /// <remarks/>
        PassportNumber,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PmtNotificationAGWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.PmtNotificationAGW.PmtNotificationAGWRq_Type PmtNotificationAGWRq;
        
        public PmtNotificationAGWRequest()
        {
        }
        
        public PmtNotificationAGWRequest(PaymentService.PmtNotificationAGW.PmtNotificationAGWRq_Type PmtNotificationAGWRq)
        {
            this.PmtNotificationAGWRq = PmtNotificationAGWRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PmtNotificationAGWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.PmtNotificationAGW.PmtNotificationAGWRs_Type PmtNotificationAGWRs;
        
        public PmtNotificationAGWResponse()
        {
        }
        
        public PmtNotificationAGWResponse(PaymentService.PmtNotificationAGW.PmtNotificationAGWRs_Type PmtNotificationAGWRs)
        {
            this.PmtNotificationAGWRs = PmtNotificationAGWRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PmtNotificationAGWChannel : PaymentService.PmtNotificationAGW.PmtNotificationAGW, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PmtNotificationAGWClient : System.ServiceModel.ClientBase<PaymentService.PmtNotificationAGW.PmtNotificationAGW>, PaymentService.PmtNotificationAGW.PmtNotificationAGW
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PmtNotificationAGWClient() : 
                base(PmtNotificationAGWClient.GetDefaultBinding(), PmtNotificationAGWClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PmtNotificationAGW.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PmtNotificationAGWClient(EndpointConfiguration endpointConfiguration) : 
                base(PmtNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), PmtNotificationAGWClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PmtNotificationAGWClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PmtNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PmtNotificationAGWClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PmtNotificationAGWClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PmtNotificationAGWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaymentService.PmtNotificationAGW.PmtNotificationAGWResponse PaymentService.PmtNotificationAGW.PmtNotificationAGW.PmtNotificationAGW(PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest request)
        {
            return base.Channel.PmtNotificationAGW(request);
        }
        
        public PaymentService.PmtNotificationAGW.PmtNotificationAGWRs_Type PmtNotificationAGW(PaymentService.PmtNotificationAGW.PmtNotificationAGWRq_Type PmtNotificationAGWRq)
        {
            PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest inValue = new PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest();
            inValue.PmtNotificationAGWRq = PmtNotificationAGWRq;
            PaymentService.PmtNotificationAGW.PmtNotificationAGWResponse retVal = ((PaymentService.PmtNotificationAGW.PmtNotificationAGW)(this)).PmtNotificationAGW(inValue);
            return retVal.PmtNotificationAGWRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentService.PmtNotificationAGW.PmtNotificationAGWResponse> PaymentService.PmtNotificationAGW.PmtNotificationAGW.PmtNotificationAGWAsync(PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest request)
        {
            return base.Channel.PmtNotificationAGWAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentService.PmtNotificationAGW.PmtNotificationAGWResponse> PmtNotificationAGWAsync(PaymentService.PmtNotificationAGW.PmtNotificationAGWRq_Type PmtNotificationAGWRq)
        {
            PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest inValue = new PaymentService.PmtNotificationAGW.PmtNotificationAGWRequest();
            inValue.PmtNotificationAGWRq = PmtNotificationAGWRq;
            return ((PaymentService.PmtNotificationAGW.PmtNotificationAGW)(this)).PmtNotificationAGWAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PmtNotificationAGW))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PmtNotificationAGW))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7001/PmtNotificationAGW");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PmtNotificationAGWClient.GetBindingForEndpoint(EndpointConfiguration.PmtNotificationAGW);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PmtNotificationAGWClient.GetEndpointAddress(EndpointConfiguration.PmtNotificationAGW);
        }
        
        public enum EndpointConfiguration
        {
            
            PmtNotificationAGW,
        }
    }
}
