//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentService.BillsMngAGW
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", ConfigurationName="PaymentService.BillsMngAGW.BillsMngAGW")]
    public interface BillsMngAGW
    {
        
        // CODEGEN: Generating message contract since the operation BillsMngAGW is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="BillsMngAGW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillRec_Type))]
        PaymentService.BillsMngAGW.BillsMngAGWResponse BillsMngAGW(PaymentService.BillsMngAGW.BillsMngAGWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BillsMngAGW", ReplyAction="*")]
        System.Threading.Tasks.Task<PaymentService.BillsMngAGW.BillsMngAGWResponse> BillsMngAGWAsync(PaymentService.BillsMngAGW.BillsMngAGWRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BillsMngAGWRq_Type
    {
        
        private MsgRqHdr_Type msgRqHdrField;
        
        private BillsMngAGWRqBody_Type bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRqHdr_Type MsgRqHdr
        {
            get
            {
                return this.msgRqHdrField;
            }
            set
            {
                this.msgRqHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BillsMngAGWRqBody_Type Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRqHdr_Type
    {
        
        private string rqUIDField;
        
        private SCId_Type sCIdField;
        
        private string funcIdField;
        
        private PartnerInfo_Type partnerInfoField;
        
        private long rqModeField;
        
        private bool rqModeFieldSpecified;
        
        private PartyId_Type partyIdField;
        
        private string userIdField;
        
        private string proxyUserIdField;
        
        private System.DateTime clientDtField;
        
        private string echoDataField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SCId_Type SCId
        {
            get
            {
                return this.sCIdField;
            }
            set
            {
                this.sCIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FuncId
        {
            get
            {
                return this.funcIdField;
            }
            set
            {
                this.funcIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PartnerInfo_Type PartnerInfo
        {
            get
            {
                return this.partnerInfoField;
            }
            set
            {
                this.partnerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long RqMode
        {
            get
            {
                return this.rqModeField;
            }
            set
            {
                this.rqModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RqModeSpecified
        {
            get
            {
                return this.rqModeFieldSpecified;
            }
            set
            {
                this.rqModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PartyId_Type PartyId
        {
            get
            {
                return this.partyIdField;
            }
            set
            {
                this.partyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ProxyUserId
        {
            get
            {
                return this.proxyUserIdField;
            }
            set
            {
                this.proxyUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime ClientDt
        {
            get
            {
                return this.clientDtField;
            }
            set
            {
                this.clientDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum SCId_Type
    {
        
        /// <remarks/>
        G2G,
        
        /// <remarks/>
        ECLLCTN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartnerInfo_Type
    {
        
        private string partnerIdField;
        
        private PartnerType_Type partnerTypeField;
        
        private string partnerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartnerType_Type PartnerType
        {
            get
            {
                return this.partnerTypeField;
            }
            set
            {
                this.partnerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartnerType_Type
    {
        
        /// <remarks/>
        GOVT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BillsMngAGWRsBody_Type
    {
        
        private string billIBANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BillIBAN
        {
            get
            {
                return this.billIBANField;
            }
            set
            {
                this.billIBANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class Status_Type
    {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc
        {
            get
            {
                return this.statusDescField;
            }
            set
            {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class MsgRsHdr_Type
    {
        
        private string rqUIDField;
        
        private string sPRefNumField;
        
        private string msgRecDtField;
        
        private Status_Type statusField;
        
        private string echoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SPRefNum
        {
            get
            {
                return this.sPRefNumField;
            }
            set
            {
                this.sPRefNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgRecDt
        {
            get
            {
                return this.msgRecDtField;
            }
            set
            {
                this.msgRecDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Status_Type Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BillsMngAGWRs_Type
    {
        
        private MsgRsHdr_Type msgRsHdrField;
        
        private BillsMngAGWRsBody_Type bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRsHdr_Type MsgRsHdr
        {
            get
            {
                return this.msgRsHdrField;
            }
            set
            {
                this.msgRsHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BillsMngAGWRsBody_Type Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class RevenueEntryInfo_Type
    {
        
        private string benAgencyIdField;
        
        private string gFSCodeField;
        
        private decimal amtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BenAgencyId
        {
            get
            {
                return this.benAgencyIdField;
            }
            set
            {
                this.benAgencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GFSCode
        {
            get
            {
                return this.gFSCodeField;
            }
            set
            {
                this.gFSCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Amt
        {
            get
            {
                return this.amtField;
            }
            set
            {
                this.amtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class POI_Type
    {
        
        private string pOINumField;
        
        private POIType_Type pOITypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string POINum
        {
            get
            {
                return this.pOINumField;
            }
            set
            {
                this.pOINumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public POIType_Type POIType
        {
            get
            {
                return this.pOITypeField;
            }
            set
            {
                this.pOITypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum POIType_Type
    {
        
        /// <remarks/>
        NAT,
        
        /// <remarks/>
        IQA,
        
        /// <remarks/>
        BIS,
        
        /// <remarks/>
        UOI,
        
        /// <remarks/>
        C700,
        
        /// <remarks/>
        GCC,
        
        /// <remarks/>
        PAS,
        
        /// <remarks/>
        BDN,
        
        /// <remarks/>
        FCN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BenInfo_Type
    {
        
        private POI_Type benPOIField;
        
        private string benNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public POI_Type BenPOI
        {
            get
            {
                return this.benPOIField;
            }
            set
            {
                this.benPOIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BenName
        {
            get
            {
                return this.benNameField;
            }
            set
            {
                this.benNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PmtOptions_Type
    {
        
        private decimal minPartialPmtAmtField;
        
        private bool minPartialPmtAmtFieldSpecified;
        
        private decimal minAdvancePmtAmtField;
        
        private bool minAdvancePmtAmtFieldSpecified;
        
        private decimal maxAdvancePmtAmtField;
        
        private bool maxAdvancePmtAmtFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal MinPartialPmtAmt
        {
            get
            {
                return this.minPartialPmtAmtField;
            }
            set
            {
                this.minPartialPmtAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinPartialPmtAmtSpecified
        {
            get
            {
                return this.minPartialPmtAmtFieldSpecified;
            }
            set
            {
                this.minPartialPmtAmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal MinAdvancePmtAmt
        {
            get
            {
                return this.minAdvancePmtAmtField;
            }
            set
            {
                this.minAdvancePmtAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinAdvancePmtAmtSpecified
        {
            get
            {
                return this.minAdvancePmtAmtFieldSpecified;
            }
            set
            {
                this.minAdvancePmtAmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal MaxAdvancePmtAmt
        {
            get
            {
                return this.maxAdvancePmtAmtField;
            }
            set
            {
                this.maxAdvancePmtAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxAdvancePmtAmtSpecified
        {
            get
            {
                return this.maxAdvancePmtAmtFieldSpecified;
            }
            set
            {
                this.maxAdvancePmtAmtFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BillSummInfo_Type
    {
        
        private decimal amtField;
        
        private AmtCode_Type amtCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Amt
        {
            get
            {
                return this.amtField;
            }
            set
            {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AmtCode_Type AmtCode
        {
            get
            {
                return this.amtCodeField;
            }
            set
            {
                this.amtCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum AmtCode_Type
    {
        
        /// <remarks/>
        MinPartialPmt,
        
        /// <remarks/>
        MinAdvancePmt,
        
        /// <remarks/>
        MaxAdvancePmt,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BillInfo_Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BillRec_Type
    {
        
        private string agencyIdField;
        
        private string billNumField;
        
        private string billAcctField;
        
        private BillAction_Type billActionField;
        
        private bool billActionFieldSpecified;
        
        private string actionReasonField;
        
        private string actionDtField;
        
        private BillStatusCode_Type billStatusCodeField;
        
        private bool billStatusCodeFieldSpecified;
        
        private string billCategoryField;
        
        private string billCycleField;
        
        private string displayLabelArField;
        
        private string displayLabelEnField;
        
        private decimal billAmtField;
        
        private string presDtField;
        
        private string dueDtField;
        
        private string expDtField;
        
        private string billRefInfoField;
        
        private string billDescField;
        
        private BillSummInfo_Type[] billSummListField;
        
        private PmtOptions_Type pmtOptionsField;
        
        private BenInfo_Type benInfoField;
        
        private RevenueEntryInfo_Type[] revenueEntryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AgencyId
        {
            get
            {
                return this.agencyIdField;
            }
            set
            {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BillNum
        {
            get
            {
                return this.billNumField;
            }
            set
            {
                this.billNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BillAcct
        {
            get
            {
                return this.billAcctField;
            }
            set
            {
                this.billAcctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public BillAction_Type BillAction
        {
            get
            {
                return this.billActionField;
            }
            set
            {
                this.billActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BillActionSpecified
        {
            get
            {
                return this.billActionFieldSpecified;
            }
            set
            {
                this.billActionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ActionReason
        {
            get
            {
                return this.actionReasonField;
            }
            set
            {
                this.actionReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ActionDt
        {
            get
            {
                return this.actionDtField;
            }
            set
            {
                this.actionDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public BillStatusCode_Type BillStatusCode
        {
            get
            {
                return this.billStatusCodeField;
            }
            set
            {
                this.billStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BillStatusCodeSpecified
        {
            get
            {
                return this.billStatusCodeFieldSpecified;
            }
            set
            {
                this.billStatusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BillCategory
        {
            get
            {
                return this.billCategoryField;
            }
            set
            {
                this.billCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BillCycle
        {
            get
            {
                return this.billCycleField;
            }
            set
            {
                this.billCycleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DisplayLabelAr
        {
            get
            {
                return this.displayLabelArField;
            }
            set
            {
                this.displayLabelArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DisplayLabelEn
        {
            get
            {
                return this.displayLabelEnField;
            }
            set
            {
                this.displayLabelEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal BillAmt
        {
            get
            {
                return this.billAmtField;
            }
            set
            {
                this.billAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PresDt
        {
            get
            {
                return this.presDtField;
            }
            set
            {
                this.presDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DueDt
        {
            get
            {
                return this.dueDtField;
            }
            set
            {
                this.dueDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ExpDt
        {
            get
            {
                return this.expDtField;
            }
            set
            {
                this.expDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BillRefInfo
        {
            get
            {
                return this.billRefInfoField;
            }
            set
            {
                this.billRefInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BillDesc
        {
            get
            {
                return this.billDescField;
            }
            set
            {
                this.billDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BillSummInfo", IsNullable=false)]
        public BillSummInfo_Type[] BillSummList
        {
            get
            {
                return this.billSummListField;
            }
            set
            {
                this.billSummListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public PmtOptions_Type PmtOptions
        {
            get
            {
                return this.pmtOptionsField;
            }
            set
            {
                this.pmtOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public BenInfo_Type BenInfo
        {
            get
            {
                return this.benInfoField;
            }
            set
            {
                this.benInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RevenueEntryInfo", IsNullable=false)]
        public RevenueEntryInfo_Type[] RevenueEntryList
        {
            get
            {
                return this.revenueEntryListField;
            }
            set
            {
                this.revenueEntryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum BillAction_Type
    {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        E,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum BillStatusCode_Type
    {
        
        /// <remarks/>
        BillNew,
        
        /// <remarks/>
        BillUpdated,
        
        /// <remarks/>
        BillExpired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BillInfo_Type : BillRec_Type
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class BillsMngAGWRqBody_Type
    {
        
        private string batchIdField;
        
        private BillInfo_Type[] billListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BatchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BillInfo", IsNullable=false)]
        public BillInfo_Type[] BillList
        {
            get
            {
                return this.billListField;
            }
            set
            {
                this.billListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public partial class PartyId_Type
    {
        
        private string partyIdNumField;
        
        private PartyIdType_Type partyIdTypeField;
        
        private bool partyIdTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartyIdNum
        {
            get
            {
                return this.partyIdNumField;
            }
            set
            {
                this.partyIdNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartyIdType_Type PartyIdType
        {
            get
            {
                return this.partyIdTypeField;
            }
            set
            {
                this.partyIdTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartyIdTypeSpecified
        {
            get
            {
                return this.partyIdTypeFieldSpecified;
            }
            set
            {
                this.partyIdTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ecp.mof.gov.sa/agw")]
    public enum PartyIdType_Type
    {
        
        /// <remarks/>
        IqamaNumber,
        
        /// <remarks/>
        NationalId,
        
        /// <remarks/>
        CommercialRegistration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("700Code")]
        Item700Code,
        
        /// <remarks/>
        AccountNumber,
        
        /// <remarks/>
        FamilyCardNumber,
        
        /// <remarks/>
        BorderNumber,
        
        /// <remarks/>
        PassportNumber,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillsMngAGWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.BillsMngAGW.BillsMngAGWRq_Type BillsMngAGWRq;
        
        public BillsMngAGWRequest()
        {
        }
        
        public BillsMngAGWRequest(PaymentService.BillsMngAGW.BillsMngAGWRq_Type BillsMngAGWRq)
        {
            this.BillsMngAGWRq = BillsMngAGWRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillsMngAGWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.ecp.mof.gov.sa/agw", Order=0)]
        public PaymentService.BillsMngAGW.BillsMngAGWRs_Type BillsMngAGWRs;
        
        public BillsMngAGWResponse()
        {
        }
        
        public BillsMngAGWResponse(PaymentService.BillsMngAGW.BillsMngAGWRs_Type BillsMngAGWRs)
        {
            this.BillsMngAGWRs = BillsMngAGWRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface BillsMngAGWChannel : PaymentService.BillsMngAGW.BillsMngAGW, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BillsMngAGWClient : System.ServiceModel.ClientBase<PaymentService.BillsMngAGW.BillsMngAGW>, PaymentService.BillsMngAGW.BillsMngAGW
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BillsMngAGWClient() : 
                base(BillsMngAGWClient.GetDefaultBinding(), BillsMngAGWClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BillsMngAGWSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillsMngAGWClient(EndpointConfiguration endpointConfiguration) : 
                base(BillsMngAGWClient.GetBindingForEndpoint(endpointConfiguration), BillsMngAGWClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillsMngAGWClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BillsMngAGWClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillsMngAGWClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BillsMngAGWClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillsMngAGWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaymentService.BillsMngAGW.BillsMngAGWResponse PaymentService.BillsMngAGW.BillsMngAGW.BillsMngAGW(PaymentService.BillsMngAGW.BillsMngAGWRequest request)
        {
            return base.Channel.BillsMngAGW(request);
        }
        
        public PaymentService.BillsMngAGW.BillsMngAGWRs_Type BillsMngAGW(PaymentService.BillsMngAGW.BillsMngAGWRq_Type BillsMngAGWRq)
        {
            PaymentService.BillsMngAGW.BillsMngAGWRequest inValue = new PaymentService.BillsMngAGW.BillsMngAGWRequest();
            inValue.BillsMngAGWRq = BillsMngAGWRq;
            PaymentService.BillsMngAGW.BillsMngAGWResponse retVal = ((PaymentService.BillsMngAGW.BillsMngAGW)(this)).BillsMngAGW(inValue);
            return retVal.BillsMngAGWRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentService.BillsMngAGW.BillsMngAGWResponse> PaymentService.BillsMngAGW.BillsMngAGW.BillsMngAGWAsync(PaymentService.BillsMngAGW.BillsMngAGWRequest request)
        {
            return base.Channel.BillsMngAGWAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentService.BillsMngAGW.BillsMngAGWResponse> BillsMngAGWAsync(PaymentService.BillsMngAGW.BillsMngAGWRq_Type BillsMngAGWRq)
        {
            PaymentService.BillsMngAGW.BillsMngAGWRequest inValue = new PaymentService.BillsMngAGW.BillsMngAGWRequest();
            inValue.BillsMngAGWRq = BillsMngAGWRq;
            return ((PaymentService.BillsMngAGW.BillsMngAGW)(this)).BillsMngAGWAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BillsMngAGWSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BillsMngAGWSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7800/BillsMngAGW");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BillsMngAGWClient.GetBindingForEndpoint(EndpointConfiguration.BillsMngAGWSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BillsMngAGWClient.GetEndpointAddress(EndpointConfiguration.BillsMngAGWSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            BillsMngAGWSOAP,
        }
    }
}
